export const EMOJI_LIST = [
  { id: 'people-emoji1', title: 'grinning face', value: '😀' },
  { id: 'people-emoji2', title: 'beaming face with smiling eyes', value: '😁' },
  { id: 'people-emoji3', title: 'face with tears of joy', value: '😂' },
  { id: 'people-emoji4', title: 'rolling on the floor laughing', value: '🤣' },
  { id: 'people-emoji5', title: 'grinning face with big eyes', value: '😃' },
  { id: 'people-emoji6', title: 'grinning face with smiling eyes', value: '😄' },
  { id: 'people-emoji7', title: 'grinning face with sweat', value: '😅' },
  { id: 'people-emoji8', title: 'grinning squinting face', value: '😆' },
  { id: 'people-emoji9', title: 'winking face', value: '😉' },
  { id: 'people-emoji10', title: 'smiling face with smiling eyes', value: '😊' },
  { id: 'people-emoji11', title: 'face savoring food', value: '😋' },
  { id: 'people-emoji12', title: 'smiling face with sunglasses', value: '😎' },
  { id: 'people-emoji13', title: 'smiling face with heart-eyes', value: '😍' },
  { id: 'people-emoji14', title: 'face blowing a kiss', value: '😘' },
  { id: 'people-emoji15', title: 'kissing face', value: '😗' },
  { id: 'people-emoji16', title: 'kissing face with smiling eyes', value: '😙' },
  { id: 'people-emoji17', title: 'kissing face with closed eyes', value: '😚' },
  { id: 'people-emoji18', title: 'slightly smiling face', value: '🙂' },
  { id: 'people-emoji19', title: 'hugging face', value: '🤗' },
  { id: 'people-emoji20', title: 'thinking face', value: '🤔' },
  { id: 'people-emoji21', title: 'neutral face ', value: '😐' },
  { id: 'people-emoji22', title: 'expressionless face', value: '😑' },
  { id: 'people-emoji23', title: 'face without mouth', value: '😶' },
  { id: 'people-emoji24', title: 'face with rolling eyes', value: '🙄' },
  { id: 'people-emoji25', title: 'smirking face', value: '😏' },
  { id: 'people-emoji26', title: 'persevering face', value: '😣' },
  { id: 'people-emoji27', title: 'sad but relieved face', value: '😥' },
  { id: 'people-emoji28', title: 'face with open mouth', value: '😮' },
  { id: 'people-emoji29', title: 'zipper-mouth face', value: '🤐' },
  { id: 'people-emoji30', title: 'hushed face', value: '😯' },
  { id: 'people-emoji31', title: 'sleepy face', value: '😪' },
  { id: 'people-emoji32', title: 'tired face', value: '😫' },
  { id: 'people-emoji33', title: 'sleeping face', value: '😴' },
  { id: 'people-emoji34', title: 'relieved face', value: '😌' },
  { id: 'people-emoji35', title: 'face with tongue', value: '😛' },
  { id: 'people-emoji36', title: 'winking face with tongue', value: '😜' },
  { id: 'people-emoji37', title: 'squinting face with tongue', value: '😝' },
  { id: 'people-emoji38', title: 'drooling face', value: '🤤' },
  { id: 'people-emoji39', title: 'unamused face', value: '😒' },
  { id: 'people-emoji40', title: 'downcast face with sweat', value: '😓' },
  { id: 'people-emoji41', title: 'pensive face', value: '😔' },
  { id: 'people-emoji42', title: 'confused face', value: '😕' },
  { id: 'people-emoji43', title: 'upside-down face', value: '🙃' },
  { id: 'people-emoji44', title: 'money-mouth face', value: '🤑' },
  { id: 'people-emoji45', title: 'astonished face', value: '😲' },
  { id: 'people-emoji46', title: 'slightly frowning face', value: '🙁' },
  { id: 'people-emoji47', title: 'confounded face', value: '😖' },
  { id: 'people-emoji48', title: 'disappointed face', value: '😞' },
  { id: 'people-emoji49', title: 'worried face', value: '😟' },
  { id: 'people-emoji50', title: 'face with steam from nose', value: '😤' },
  { id: 'people-emoji51', title: 'crying face', value: '😢' },
  { id: 'people-emoji52', title: 'loudly crying face', value: '😭' },
  { id: 'people-emoji53', title: 'frowning face with open mouth', value: '😦' },
  { id: 'people-emoji54', title: 'anguished face', value: '😧' },
  { id: 'people-emoji55', title: 'fearful face', value: '😨' },
  { id: 'people-emoji56', title: 'weary face', value: '😩' },
  { id: 'people-emoji57', title: 'grimacing face', value: '😬' },
  { id: 'people-emoji58', title: 'anxious face with sweat', value: '😰' },
  { id: 'people-emoji59', title: 'face screaming in fear', value: '😱' },
  { id: 'people-emoji60', title: 'flushed face', value: '😳' },
  { id: 'people-emoji61', title: 'dizzy face', value: '😵' },
  { id: 'people-emoji62', title: 'pouting face', value: '😡' },
  { id: 'people-emoji63', title: 'angry face', value: '😠' },
  { id: 'people-emoji64', title: 'face with medical mask', value: '😷' },
  { id: 'people-emoji65', title: 'face with thermometer', value: '🤒' },
  { id: 'people-emoji66', title: 'face with head-bandage', value: '🤕' },
  { id: 'people-emoji67', title: 'nauseated face', value: '🤢' },
  { id: 'people-emoji68', title: 'sneezing face', value: '🤧' },
  { id: 'people-emoji69', title: 'smiling face with halo', value: '😇' },
  { id: 'people-emoji70', title: 'cowboy hat face', value: '🤠' },
  { id: 'people-emoji71', title: 'lying face', value: '🤥' },
  { id: 'people-emoji72', title: 'nerd face', value: '🤓' },
  { id: 'people-emoji73', title: 'smiling face with horns', value: '😈' },
  { id: 'people-emoji74', title: 'angry face with horns', value: '👿' },
  { id: 'people-emoji75', title: 'clown face', value: '🤡' },
  { id: 'people-emoji76', title: 'ogre', value: '👹' },
  { id: 'people-emoji77', title: 'goblin', value: '👺' },
  { id: 'people-emoji78', title: 'skull', value: '💀' },
  { id: 'people-emoji79', title: 'skull and crossbones', value: '☠' },
  { id: 'people-emoji80', title: 'ghost', value: '👻' },
  { id: 'people-emoji81', title: 'alien', value: '👽' },
  { id: 'people-emoji82', title: 'alien monster', value: '👾' },
  { id: 'people-emoji83', title: 'robot face', value: '🤖' },
  { id: 'people-emoji84', title: 'pile of poo', value: '💩' },
  { id: 'people-emoji85', title: 'grinning cat face', value: '😺' },
  { id: 'people-emoji86', title: 'grinning cat face with smiling eyes', value: '😸' },
  { id: 'people-emoji87', title: 'cat face with tears of joy', value: '😹' },
  { id: 'people-emoji88', title: 'smiling cat face with heart-eyes', value: '😻' },
  { id: 'people-emoji89', title: 'cat face with wry smile', value: '😼' },
  { id: 'people-emoji90', title: 'kissing cat face', value: '😽' },
  { id: 'people-emoji91', title: 'weary cat face', value: '🙀' },
  { id: 'people-emoji92', title: 'crying cat face', value: '😿' },
  { id: 'people-emoji93', title: 'pouting cat face', value: '😾' },
  { id: 'people-emoji94', title: 'see-no-evil monkey', value: '🙈' },
  { id: 'people-emoji95', title: 'hear-no-evil monkey', value: '🙉' },
  { id: 'people-emoji96', title: 'speak-no-evil monkey', value: '🙊' },
  { id: 'people-emoji97', title: 'baby', value: '👶' },
  { id: 'people-emoji98', title: 'boy', value: '👦' },
  { id: 'people-emoji99', title: 'girl', value: '👧' },
  { id: 'people-emoji100', title: 'man', value: '👨' },
  { id: 'people-emoji101', title: 'woman', value: '👩' },
  { id: 'people-emoji102', title: 'old man', value: '👴' },
  { id: 'people-emoji103', title: 'old woman', value: '👵' },
  { id: 'people-emoji104', title: 'man health worker', value: '👨‍⚕️' },
  { id: 'people-emoji105', title: 'woman health worker', value: '👩‍⚕️' },
  { id: 'people-emoji106', title: 'man student', value: '👨‍🎓' },
  { id: 'people-emoji107', title: 'woman student', value: '👩‍🎓' },
  { id: 'people-emoji108', title: 'man teacher', value: '👨‍🏫' },
  { id: 'people-emoji109', title: 'woman teacher', value: '👩‍🏫' },
  { id: 'people-emoji110', title: 'man judge', value: '👨‍⚖️' },
  { id: 'people-emoji111', title: 'woman judge', value: '👩‍⚖️' },
  { id: 'people-emoji112', title: 'man farmer', value: '👨‍🌾' },
  { id: 'people-emoji113', title: 'woman farmer', value: '👩‍🌾' },
  { id: 'people-emoji114', title: 'man cook', value: '👨‍🍳' },
  { id: 'people-emoji115', title: 'woman cook', value: '👩‍🍳' },
  { id: 'people-emoji116', title: 'man mechanic', value: '👨‍🔧' },
  { id: 'people-emoji117', title: 'woman mechanic', value: '👩‍🔧' },
  { id: 'people-emoji118', title: 'man factory worker', value: '👨‍🏭' },
  { id: 'people-emoji119', title: 'woman factory worker', value: '👩‍🏭' },
  { id: 'people-emoji120', title: 'man office worker', value: '👨‍💼' },
  { id: 'people-emoji121', title: 'woman office worker', value: '👩‍💼' },
  { id: 'people-emoji122', title: 'man scientist', value: '👨‍🔬' },
  { id: 'people-emoji123', title: 'woman scientist', value: '👩‍🔬' },
  { id: 'people-emoji124', title: 'man technologist', value: '👨‍💻' },
  { id: 'people-emoji125', title: 'woman technologist', value: '👩‍💻' },
  { id: 'people-emoji126', title: 'man singer', value: '👨‍🎤' },
  { id: 'people-emoji127', title: 'woman singer', value: '👩‍🎤' },
  { id: 'people-emoji128', title: 'man artist', value: '👨‍🎨' },
  { id: 'people-emoji129', title: 'woman artist', value: '👩‍🎨' },
  { id: 'people-emoji130', title: 'man pilot', value: '👨‍✈️' },
  { id: 'people-emoji131', title: 'woman pilot', value: '👩‍✈️' },
  { id: 'people-emoji132', title: 'man astronaut', value: '👨‍🚀' },
  { id: 'people-emoji133', title: 'woman astronaut', value: '👩‍🚀' },
  { id: 'people-emoji134', title: 'man firefighter', value: '👨‍🚒' },
  { id: 'people-emoji135', title: 'woman firefighter', value: '👩‍🚒' },
  { id: 'people-emoji136', title: 'man police officer', value: '👮‍♂️' },
  //   { id: 'people-emoji110', title: '', value: ' 👮‍♀‍🕵‍♂️' },
  { id: 'people-emoji137', title: 'woman police officer', value: '🕵‍♀️' },
  { id: 'people-emoji138', title: 'man guard', value: '💂‍♂️' },
  { id: 'people-emoji139', title: 'womanman construction worker guard', value: '💂‍♀️' },
  { id: 'people-emoji140', title: 'man construction worker', value: '👷‍♂️' },
  { id: 'people-emoji141', title: 'woman construction worker', value: '👷‍♀️' },
  { id: 'people-emoji142', title: 'prince', value: '🤴' },
  { id: 'people-emoji143', title: 'princessman wearing turban', value: '👸' },
  { id: 'people-emoji144', title: 'man wearing turban', value: '👳‍♂️' },
  { id: 'people-emoji145', title: 'woman wearing turban', value: '👳‍♀️' },
  { id: 'people-emoji146', title: 'man with Chinese cap', value: '👲' },
  { id: 'people-emoji147', title: 'blond-haired man', value: '👱‍♂️' },
  { id: 'people-emoji148', title: 'blond-haired woman', value: '👱‍♀️' },
  { id: 'people-emoji149', title: 'man in tuxedo', value: '🤵' },
  { id: 'people-emoji150', title: 'bride with veil', value: '👰' },
  { id: 'people-emoji151', title: 'pregnant woman', value: '🤰' },
  { id: 'people-emoji152', title: 'baby angel', value: '👼' },
  { id: 'people-emoji153', title: 'Santa Claus', value: '🎅' },
  { id: 'people-emoji154', title: 'Mrs. Claus', value: '🤶' },
  { id: 'people-emoji155', title: 'man frowning', value: '🙍‍♂️' },
  { id: 'people-emoji156', title: 'woman frowning', value: '🙍‍♀️' },
  { id: 'people-emoji157', title: 'man pouting', value: '🙎‍♂️' },
  { id: 'people-emoji158', title: 'woman pouting', value: '🙎‍♀️' },
  { id: 'people-emoji159', title: 'man gesturing NO', value: '🙅‍♂️' },
  { id: 'people-emoji160', title: 'woman gesturing NO', value: '🙅‍♀️' },
  { id: 'people-emoji161', title: 'man gesturing OK', value: '🙆‍♂️' },
  { id: 'people-emoji162', title: 'woman gesturing OK', value: '🙆‍♀️' },
  { id: 'people-emoji163', title: 'man tipping hand', value: '💁‍♂️' },
  { id: 'people-emoji164', title: 'woman tipping hand', value: '💁‍♀️' },
  { id: 'people-emoji165', title: 'man raising hand', value: '🙋‍♂️' },
  { id: 'people-emoji166', title: 'woman raising hand', value: '🙋‍♀️' },
  { id: 'people-emoji167', title: 'man bowing', value: '🙇‍♂️' },
  { id: 'people-emoji168', title: 'woman bowing', value: '🙇‍♀️' },
  { id: 'people-emoji169', title: 'man facepalming', value: '🤦‍♂️' },
  { id: 'people-emoji170', title: 'woman facepalming', value: '🤦‍♀️' },
  { id: 'people-emoji171', title: 'man shrugging', value: '🤷‍♂️' },
  { id: 'people-emoji172', title: 'woman shrugging', value: '🤷‍♀️' },
  { id: 'people-emoji173', title: 'man getting massage', value: '💆‍♂️' },
  { id: 'people-emoji174', title: 'woman getting massage', value: '💆‍♀️' },
  { id: 'people-emoji175', title: 'man getting haircut', value: '💇‍♂️' },
  { id: 'people-emoji176', title: 'woman getting haircut', value: '💇‍♀️' },
  { id: 'people-emoji177', title: 'man walking', value: '🚶‍♂️' },
  { id: 'people-emoji178', title: 'woman walking', value: '🚶‍♀️' },
  { id: 'people-emoji179', title: 'man running', value: '🏃‍♂️' },
  { id: 'people-emoji180', title: 'woman running', value: '🏃‍♀️' },
  { id: 'people-emoji181', title: 'man dancing', value: '💃' },
  { id: 'people-emoji182', title: 'woman dancing', value: '🕺' },
  { id: 'people-emoji183', title: 'people with bunny ears', value: '👯' },
  { id: 'people-emoji184', title: 'men with bunny ears', value: '👯‍♂️' },
  { id: 'people-emoji185', title: 'woman with bunny ears', value: '👯‍♀️' },
  { id: 'people-emoji186', title: 'person taking bath', value: '🛀' },
  { id: 'people-emoji187', title: 'speaking head', value: '🗣' },
  { id: 'people-emoji188', title: 'bust in silhouette', value: '👤' },
  { id: 'people-emoji189', title: 'busts in silhouette', value: '👥' },
  { id: 'people-emoji190', title: 'person fencing', value: '🤺' },
  { id: 'people-emoji191', title: 'horse racing', value: '🏇' },
  { id: 'people-emoji192', title: 'skier', value: '⛷' },
  { id: 'people-emoji193', title: 'snowboarder', value: '🏂' },
  { id: 'people-emoji194', title: 'man surfing', value: '🏄‍♂️' },
  { id: 'people-emoji195', title: 'woman surfing', value: '🏄‍♀️' },
  { id: 'people-emoji196', title: 'man rowing boat', value: '🚣‍♂️' },
  { id: 'people-emoji197', title: 'woman rowing boat', value: '🚣‍♀️' },
  { id: 'people-emoji198', title: 'man swimming', value: '🏊‍♂️' },
  { id: 'people-emoji199', title: 'woman swimming', value: '🏊‍♀️' },
  { id: 'people-emoji200', title: 'man lifting weights', value: '🏋‍♂️' },
  { id: 'people-emoji201', title: 'woman lifting weights', value: '🏋‍♀️' },
  { id: 'people-emoji202', title: 'man biking', value: '🚴‍♂️' },
  { id: 'people-emoji203', title: 'woman biking', value: '🚴‍♀️' },
  { id: 'people-emoji204', title: 'man mountain biking', value: '🚵‍♂️' },
  { id: 'people-emoji205', title: 'woman mountain biking', value: '🚵‍♀️' },
  { id: 'people-emoji206', title: 'racing car', value: '🏎' },
  { id: 'people-emoji207', title: 'motorcycle', value: '🏍' },
  { id: 'people-emoji-209', title: '', value: '🤸‍♂️' },
  { id: 'people-emoji-210', title: '', value: '🤸‍♀️' },
  { id: 'people-emoji-211', title: '', value: '🤼' },
  { id: 'people-emoji-212', title: '', value: '🤼‍♂️' },
  { id: 'people-emoji-213', title: '', value: '🤼‍♀️' },
  { id: 'people-emoji-214', title: '', value: '🤽‍♂️' },
  { id: 'people-emoji-215', title: '', value: '🤽‍♀️' },
  { id: 'people-emoji-216', title: '', value: '🤾‍♂️' },
  { id: 'people-emoji-217', title: '', value: '🤾‍♀️' },
  { id: 'people-emoji-218', title: '', value: '🤹‍♂️' },
  { id: 'people-emoji-219', title: '', value: '🤹‍♀️' },
  { id: 'people-emoji-220', title: '', value: '👫' },
  { id: 'people-emoji-221', title: '', value: '👬' },
  { id: 'people-emoji-222', title: '', value: '👭' },
  { id: 'people-emoji-223', title: '', value: '💏' },
  { id: 'people-emoji-224', title: '', value: '👩‍❤️‍💋‍👨' },
  { id: 'people-emoji-225', title: '', value: '👨‍❤️‍💋‍👨' },
  { id: 'people-emoji-226', title: '', value: '👩‍❤️‍💋‍👩' },
  { id: 'people-emoji-227', title: '', value: '💑' },
  { id: 'people-emoji-228', title: '', value: '👩‍❤️‍👨' },
  { id: 'people-emoji-229', title: '', value: '👨‍❤️‍👨' },
  { id: 'people-emoji-230', title: '', value: '👩‍❤️‍👩' },
  { id: 'people-emoji-231', title: '', value: '👪' },
  { id: 'people-emoji-232', title: '', value: '👨‍👩‍👦' },
  { id: 'people-emoji-233', title: '', value: '👨‍👩‍👧' },
  { id: 'people-emoji-234', title: '', value: '👨‍👩‍👧‍👦' },
  { id: 'people-emoji-235', title: '', value: '👨‍👩‍👦‍👦' },
  { id: 'people-emoji-236', title: '', value: '👨‍👩‍👧‍👧' },
  { id: 'people-emoji-237', title: '', value: '👨‍👨‍👦' },
  { id: 'people-emoji-238', title: '', value: '👨‍👨‍👧' },
  { id: 'people-emoji-239', title: '', value: '👨‍👨‍👧‍👦' },
  { id: 'people-emoji-240', title: '', value: '👨‍👨‍👦‍👦' },
  { id: 'people-emoji-241', title: '', value: '👨‍👨‍👧‍👧' },
  { id: 'people-emoji-242', title: '', value: '👩‍👩‍👦' },
  { id: 'people-emoji-243', title: '', value: '👩‍👩‍👧' },
  { id: 'people-emoji-244', title: '', value: '👩‍👩‍👧‍👦' },
  { id: 'people-emoji-245', title: '', value: '👩‍👩‍👦‍👦' },
  { id: 'people-emoji-246', title: '', value: '👩‍👩‍👧‍👧' },
  { id: 'people-emoji-247', title: '', value: '👨‍👦' },
  { id: 'people-emoji-248', title: '', value: '👨‍👦‍👦' },
  { id: 'people-emoji-249', title: '', value: '👨‍👧' },
  { id: 'people-emoji-250', title: '', value: '👨‍👧‍👦' },
  { id: 'people-emoji-251', title: '', value: '👨‍👧‍👧' },
  { id: 'people-emoji-252', title: '', value: '👩‍👦' },
  { id: 'people-emoji-253', title: '', value: '👩‍👦‍👦' },
  { id: 'people-emoji-254', title: '', value: '👩‍👧' },
  { id: 'people-emoji-255', title: '', value: '👩‍👧‍👦' },
  { id: 'people-emoji-256', title: '', value: '👩‍👧‍👧' },
  { id: 'people-emoji-257', title: '', value: '🤳' },
  { id: 'people-emoji-258', title: '', value: '💪' },
  { id: 'people-emoji-259', title: '', value: '👈' },
  { id: 'people-emoji-260', title: '', value: '👉' },
  { id: 'people-emoji-261', title: '', value: '☝' },
  { id: 'people-emoji-272', title: '', value: '👆' },
  { id: 'people-emoji-273', title: '', value: '🖕' },
  { id: 'people-emoji-274', title: '', value: '👇' },
  { id: 'people-emoji-275', title: '', value: '✌' },
  { id: 'people-emoji-276', title: '', value: '🤞' },
  { id: 'people-emoji-277', title: '', value: '🖖' },
  { id: 'people-emoji-278', title: '', value: '🤘' },
  { id: 'people-emoji-279', title: '', value: '🤙' },
  { id: 'people-emoji-282', title: '', value: '🖐' },
  { id: 'people-emoji-283', title: '', value: '✋' },
  { id: 'people-emoji-284', title: '', value: '👌' },
  { id: 'people-emoji-285', title: '', value: '👍' },
  { id: 'people-emoji-286', title: '', value: '👎' },
  { id: 'people-emoji-287', title: '', value: '✊' },
  { id: 'people-emoji-288', title: '', value: '👊' },
  { id: 'people-emoji-289', title: '', value: '🤛' },
  { id: 'people-emoji-290', title: '', value: '🤜' },
  { id: 'people-emoji-292', title: '', value: '🤚' },
  { id: 'people-emoji-293', title: '', value: '👋' },
  { id: 'people-emoji-294', title: '', value: '✍' },
  { id: 'people-emoji-295', title: '', value: '👏' },
  { id: 'people-emoji-296', title: '', value: '👐' },
  { id: 'people-emoji-297', title: '', value: '🙌' },
  { id: 'people-emoji-298', title: '', value: '🙏' },
  { id: 'people-emoji-299', title: '', value: '🤝' },
  { id: 'people-emoji-300', title: '', value: '💅' },
  { id: 'people-emoji-300.4', title: '', value: '👂' },
  { id: 'people-emoji-301', title: '', value: '👃' },
  { id: 'people-emoji-302', title: '', value: '👣' },
  { id: 'people-emoji-303', title: '', value: '👀' },
  { id: 'people-emoji-304', title: '', value: '👁' },
  { id: 'people-emoji-305', title: '', value: '👁️‍🗨️' },
  { id: 'people-emoji-306', title: '', value: '👅' },
  { id: 'people-emoji-307', title: '', value: '👄' },
  { id: 'people-emoji-308', title: '', value: '💋' },
  { id: 'people-emoji-309', title: '', value: '💘' },
  { id: 'people-emoji-310', title: '', value: '❤' },
  { id: 'people-emoji-311', title: '', value: '💓' },
  { id: 'people-emoji-312', title: '', value: '💔' },
  { id: 'people-emoji-313', title: '', value: '💕' },
  { id: 'people-emoji-314', title: '', value: '💖' },
  { id: 'people-emoji-315', title: '', value: '💗' },
  { id: 'people-emoji-316', title: '', value: '💙' },
  { id: 'people-emoji-317', title: '', value: '💚' },
  { id: 'people-emoji-318', title: '', value: '💛' },
  { id: 'people-emoji-319', title: '', value: '💜' },
  { id: 'people-emoji-320', title: '', value: '🖤' },
  { id: 'people-emoji-321', title: '', value: '💝' },
  { id: 'people-emoji-222', title: '', value: '💞' },
  { id: 'people-emoji-223', title: '', value: '💟' },
  { id: 'people-emoji-224', title: '', value: '❣' },
  { id: 'people-emoji-225', title: '', value: '💌' },
  { id: 'people-emoji-226', title: '', value: '💤' },
  { id: 'people-emoji-227', title: '', value: '💢' },
  { id: 'people-emoji-228', title: '', value: '💣' },
  { id: 'people-emoji-229', title: '', value: '💥' },
  { id: 'people-emoji-330', title: '', value: '💦' },
  { id: 'people-emoji-331', title: '', value: '💨' },
  { id: 'people-emoji-332', title: '', value: '💫' },
  { id: 'people-emoji-333', title: '', value: '💬' },
  { id: 'people-emoji-334', title: '', value: '🗨' },
  { id: 'people-emoji-335', title: '', value: '🗯' },
  { id: 'people-emoji-336', title: '', value: '💭' },
  { id: 'people-emoji-337', title: '', value: '🕳' },
  { id: 'people-emoji-338', title: '', value: '👓' },
  { id: 'people-emoji-339', title: '', value: '🕶' },
  { id: 'people-emoji-340', title: '', value: '👔' },
  { id: 'people-emoji-341', title: '', value: '👕' },
  { id: 'people-emoji-342', title: '', value: '👖' },
  { id: 'people-emoji-343', title: '', value: '👗' },
  { id: 'people-emoji-344', title: '', value: '👘' },
  { id: 'people-emoji-345', title: '', value: '👙' },
  { id: 'people-emoji-346', title: '', value: '👚' },
  { id: 'people-emoji-347', title: '', value: '👛' },
  { id: 'people-emoji-348', title: '', value: '👜' },
  { id: 'people-emoji-349', title: '', value: '👝' },
  { id: 'people-emoji-350', title: '', value: '🛍' },
  { id: 'people-emoji-351', title: '', value: '🎒' },
  { id: 'people-emoji-352', title: '', value: '👞' },
  { id: 'people-emoji-353', title: '', value: '👟' },
  { id: 'people-emoji-354', title: '', value: '👠' },
  { id: 'people-emoji-355', title: '', value: '👡' },
  { id: 'people-emoji-356', title: '', value: '👢' },
  { id: 'people-emoji-357', title: '', value: '👑' },
  { id: 'people-emoji-358', title: '', value: '👒' },
  { id: 'people-emoji-359', title: '', value: '🎩' },
  { id: 'people-emoji-360', title: '', value: '🎓' },
  { id: 'people-emoji-361', title: '', value: '⛑' },
  { id: 'people-emoji-362', title: '', value: '📿' },
  { id: 'people-emoji-363', title: '', value: '💄' },
  { id: 'people-emoji-364', title: '', value: '💍' },
  { id: 'people-emoji-365', title: '', value: '💎' },
  { id: 'people-emoji-366', title: '', value: '🤩' },
  { id: 'people-emoji-367', title: '', value: '🤨' },
  { id: 'people-emoji-368', title: '', value: '🤯' },
  { id: 'people-emoji-369', title: '', value: '🤪' },
  { id: 'people-emoji-370', title: '', value: '🤬' },
  { id: 'people-emoji-371', title: '', value: '🤮' },
  { id: 'people-emoji-372', title: '', value: '🤫' },
  { id: 'people-emoji-373', title: '', value: '🤭' },
  { id: 'people-emoji-374', title: '', value: '🧐' },
  { id: 'people-emoji-375', title: '', value: '🧒' },
  { id: 'people-emoji-376', title: '', value: '🧑' },
  { id: 'people-emoji-377', title: '', value: '🧓' },
  { id: 'people-emoji-378', title: '', value: '🧕' },
  { id: 'people-emoji-379', title: '', value: '🧔' },
  { id: 'people-emoji-380', title: '', value: '🤱' },
  { id: 'people-emoji-381', title: '', value: '🧙‍♀️' },
  { id: 'people-emoji-382', title: '', value: '🧙‍♂️' },
  { id: 'people-emoji-383', title: '', value: '🧚‍♀️' },
  { id: 'people-emoji-384', title: '', value: '🧚‍♂️' },
  { id: 'people-emoji-385', title: '', value: '🧛‍♀️' },
  { id: 'people-emoji-386', title: '', value: '🧛‍♂️' },
  { id: 'people-emoji-387', title: '', value: '🧜‍♀️' },
  { id: 'people-emoji-388', title: '', value: '🧜‍♂️' },
  { id: 'people-emoji-389', title: '', value: '🧝‍♀️' },
  { id: 'people-emoji-390', title: '', value: '🧝‍♂️' },
  { id: 'people-emoji-391', title: '', value: '🧞‍♀️' },
  { id: 'people-emoji-392', title: '', value: '🧞‍♂️' },
  { id: 'people-emoji-393', title: '', value: '🧟‍♀️' },
  { id: 'people-emoji-394', title: '', value: '🧟‍♂️' },
  { id: 'people-emoji-395', title: '', value: '🧖‍♀️' },
  { id: 'people-emoji-396', title: '', value: '🧖‍♂️' },
  { id: 'people-emoji-397', title: '', value: '🧗‍♀️' },
  { id: 'people-emoji-398', title: '', value: '🧗‍♂️' },
  { id: 'people-emoji-399', title: '', value: '🧘‍♀️' },
  { id: 'people-emoji-400', title: '', value: '🧘‍♂️' },
  { id: 'people-emoji-401', title: '', value: '🛌' },
  { id: 'people-emoji-402', title: '', value: '🕴' },
  { id: 'people-emoji-403', title: '', value: '🏌‍♂️' },
  { id: 'people-emoji-404', title: '', value: '🏌‍♀️' },
  { id: 'people-emoji-405', title: '', value: '⛹‍♂️' },
  { id: 'people-emoji-406', title: '', value: '⛹‍♀️' },
  { id: 'people-emoji-407', title: '', value: '🤟' },
  { id: 'people-emoji-408', title: '', value: '🤲' },
  { id: 'people-emoji-409', title: '', value: '🧠' },
  { id: 'people-emoji-411', title: '', value: '🧡' },
  { id: 'people-emoji-412', title: '', value: '🧣' },
  { id: 'people-emoji-413', title: '', value: '🧤' },
  { id: 'people-emoji-414', title: '', value: '🧥' },
  { id: 'people-emoji-415', title: '', value: '🧦' },
  { id: 'people-emoji-416', title: '', value: '🧢' },
  // Nature
  { id: 'nature-emoji-1', title: '', value: '🐵' },
  { id: 'nature-emoji-2', title: '', value: '🐒' },
  { id: 'nature-emoji-3', title: '', value: '🦍' },
  { id: 'nature-emoji-4', title: '', value: '🐶' },
  { id: 'nature-emoji-5', title: '', value: '🐕' },
  { id: 'nature-emoji-6', title: '', value: '🐩' },
  { id: 'nature-emoji-7', title: '', value: '🐺' },
  { id: 'nature-emoji-8', title: '', value: '🦊' },
  { id: 'nature-emoji-9', title: '', value: '🐱' },
  { id: 'nature-emoji-10', title: '', value: '🐈' },
  { id: 'nature-emoji-11', title: '', value: '🦁' },
  { id: 'nature-emoji-12', title: '', value: '🐯' },
  { id: 'nature-emoji-13', title: '', value: '🐅' },
  { id: 'nature-emoji-14', title: '', value: '🐆' },
  { id: 'nature-emoji-15', title: '', value: '🐴' },
  { id: 'nature-emoji-16', title: '', value: '🐎' },
  { id: 'nature-emoji-17', title: '', value: '🦄' },
  { id: 'nature-emoji-18', title: '', value: '🦌' },
  { id: 'nature-emoji-19', title: '', value: '🐮' },
  { id: 'nature-emoji-20', title: '', value: '🐂' },
  { id: 'nature-emoji-21', title: '', value: '🐃' },
  { id: 'nature-emoji-22', title: '', value: '🐄' },
  { id: 'nature-emoji-23', title: '', value: '🐷' },
  { id: 'nature-emoji-24', title: '', value: '🐖' },
  { id: 'nature-emoji-25', title: '', value: '🐗' },
  { id: 'nature-emoji-26', title: '', value: '🐽' },
  { id: 'nature-emoji-27', title: '', value: '🐏' },
  { id: 'nature-emoji-28', title: '', value: '🐑' },
  { id: 'nature-emoji-29', title: '', value: '🐐' },
  { id: 'nature-emoji-30', title: '', value: '🐪' },
  { id: 'nature-emoji-31', title: '', value: '🐫' },
  { id: 'nature-emoji-32', title: '', value: '🐘' },
  { id: 'nature-emoji-33', title: '', value: '🦏' },
  { id: 'nature-emoji-34', title: '', value: '🐭' },
  { id: 'nature-emoji-35', title: '', value: '🐁' },
  { id: 'nature-emoji-36', title: '', value: '🐀' },
  { id: 'nature-emoji-37', title: '', value: '🐹' },
  { id: 'nature-emoji-38', title: '', value: '🐰' },
  { id: 'nature-emoji-39', title: '', value: '🐇' },
  { id: 'nature-emoji-40', title: '', value: '🐿' },
  { id: 'nature-emoji-41', title: '', value: '🦇' },
  { id: 'nature-emoji-42', title: '', value: '🐻' },
  { id: 'nature-emoji-43', title: '', value: '🐨' },
  { id: 'nature-emoji-44', title: '', value: '🐼' },
  { id: 'nature-emoji-45', title: '', value: '🐾' },
  { id: 'nature-emoji-46', title: '', value: '🦃' },
  { id: 'nature-emoji-47', title: '', value: '🐔' },
  { id: 'nature-emoji-48', title: '', value: '🐓' },
  { id: 'nature-emoji-49', title: '', value: '🐣' },
  { id: 'nature-emoji-50', title: '', value: '🐤' },
  { id: 'nature-emoji-51', title: '', value: '🐥' },
  { id: 'nature-emoji-52', title: '', value: '🐦' },
  { id: 'nature-emoji-53', title: '', value: '🐧' },
  { id: 'nature-emoji-54', title: '', value: '🕊' },
  { id: 'nature-emoji-55', title: '', value: '🦅' },
  { id: 'nature-emoji-56', title: '', value: '🦆' },
  { id: 'nature-emoji-57', title: '', value: '🦉' },
  { id: 'nature-emoji-58', title: '', value: '🐸' },
  { id: 'nature-emoji-59', title: '', value: '🐊' },
  { id: 'nature-emoji-60', title: '', value: '🐢' },
  { id: 'nature-emoji-61', title: '', value: '🦎' },
  { id: 'nature-emoji-62', title: '', value: '🐍' },
  { id: 'nature-emoji-63', title: '', value: '🐲' },
  { id: 'nature-emoji-64', title: '', value: '🐉' },
  { id: 'nature-emoji-65', title: '', value: '🐳' },
  { id: 'nature-emoji-66', title: '', value: '🐋' },
  { id: 'nature-emoji-67', title: '', value: '🐬' },
  { id: 'nature-emoji-68', title: '', value: '🐟' },
  { id: 'nature-emoji-69', title: '', value: '🐠' },
  { id: 'nature-emoji-70', title: '', value: '🐡' },
  { id: 'nature-emoji-71', title: '', value: '🦈' },
  { id: 'nature-emoji-72', title: '', value: '🐙' },
  { id: 'nature-emoji-73', title: '', value: '🐚' },
  { id: 'nature-emoji-74', title: '', value: '🦀' },
  { id: 'nature-emoji-75', title: '', value: '🦐' },
  { id: 'nature-emoji-76', title: '', value: '🦑' },
  { id: 'nature-emoji-77', title: '', value: '🐌' },
  { id: 'nature-emoji-78', title: '', value: '🦋' },
  { id: 'nature-emoji-79', title: '', value: '🐛' },
  { id: 'nature-emoji-80', title: '', value: '🐜' },
  { id: 'nature-emoji-81', title: '', value: '🐝' },
  { id: 'nature-emoji-82', title: '', value: '🐞' },
  { id: 'nature-emoji-83', title: '', value: '🕷' },
  { id: 'nature-emoji-84', title: '', value: '🕸' },
  { id: 'nature-emoji-85', title: '', value: '🦂' },
  { id: 'nature-emoji-86', title: '', value: '💐' },
  { id: 'nature-emoji-87', title: '', value: '🌸' },
  { id: 'nature-emoji-88', title: '', value: '💮' },
  { id: 'nature-emoji-89', title: '', value: '🏵' },
  { id: 'nature-emoji-90', title: '', value: '🌹' },
  { id: 'nature-emoji-91', title: '', value: '🥀' },
  { id: 'nature-emoji-92', title: '', value: '🌺' },
  { id: 'nature-emoji-93', title: '', value: '🌻' },
  { id: 'nature-emoji-94', title: '', value: '🌼' },
  { id: 'nature-emoji-95', title: '', value: '🌷' },
  { id: 'nature-emoji-96', title: '', value: '🌱' },
  { id: 'nature-emoji-97', title: '', value: '🌲' },
  { id: 'nature-emoji-98', title: '', value: '🌳' },
  { id: 'nature-emoji-99', title: '', value: '🌴' },
  { id: 'nature-emoji-100', title: '', value: '🌵' },
  { id: 'nature-emoji-101', title: '', value: '🌾' },
  { id: 'nature-emoji-102', title: '', value: '🌿' },
  { id: 'nature-emoji-103', title: '', value: '☘' },
  { id: 'nature-emoji-104', title: '', value: '🍀' },
  { id: 'nature-emoji-105', title: '', value: '🍁' },
  { id: 'nature-emoji-106', title: '', value: '🍂' },
  { id: 'nature-emoji-107', title: '', value: '🍃' },
  { id: 'nature-emoji-108', title: '', value: '🦓' },
  { id: 'nature-emoji-109', title: '', value: '🦒' },
  { id: 'nature-emoji-110', title: '', value: '🦔' },
  { id: 'nature-emoji-111', title: '', value: '🦕' },
  { id: 'nature-emoji-112', title: '', value: '🦖' },
  { id: 'nature-emoji-113', title: '', value: '🦗' },
  // Food & Drink
  { id: 'food-emoji-0', title: '', value: '🍇' },
  { id: 'food-emoji-1', title: '', value: '🍈' },
  { id: 'food-emoji-2', title: '', value: '🍉' },
  { id: 'food-emoji-3', title: '', value: '🍊' },
  { id: 'food-emoji-4', title: '', value: '🍋' },
  { id: 'food-emoji-5', title: '', value: '🍌' },
  { id: 'food-emoji-6', title: '', value: '🍍' },
  { id: 'food-emoji-7', title: '', value: '🍎' },
  { id: 'food-emoji-8', title: '', value: '🍏' },
  { id: 'food-emoji-9', title: '', value: '🍐' },
  { id: 'food-emoji-10', title: '', value: '🍑' },
  { id: 'food-emoji-11', title: '', value: '🍒' },
  { id: 'food-emoji-12', title: '', value: '🍓' },
  { id: 'food-emoji-13', title: '', value: '🥝' },
  { id: 'food-emoji-14', title: '', value: '🍅' },
  { id: 'food-emoji-15', title: '', value: '🥑' },
  { id: 'food-emoji-16', title: '', value: '🍆' },
  { id: 'food-emoji-17', title: '', value: '🥔' },
  { id: 'food-emoji-18', title: '', value: '🥕' },
  { id: 'food-emoji-19', title: '', value: '🌽' },
  { id: 'food-emoji-20', title: '', value: '🌶' },
  { id: 'food-emoji-21', title: '', value: '🥒' },
  { id: 'food-emoji-22', title: '', value: '🍄' },
  { id: 'food-emoji-23', title: '', value: '🥜' },
  { id: 'food-emoji-24', title: '', value: '🌰' },
  { id: 'food-emoji-25', title: '', value: '🍞' },
  { id: 'food-emoji-26', title: '', value: '🥐' },
  { id: 'food-emoji-27', title: '', value: '🥖' },
  { id: 'food-emoji-28', title: '', value: '🥞' },
  { id: 'food-emoji-29', title: '', value: '🧀' },
  { id: 'food-emoji-30', title: '', value: '🍖' },
  { id: 'food-emoji-31', title: '', value: '🍗' },
  { id: 'food-emoji-32', title: '', value: '🥓' },
  { id: 'food-emoji-33', title: '', value: '🍔' },
  { id: 'food-emoji-34', title: '', value: '🍟' },
  { id: 'food-emoji-35', title: '', value: '🍕' },
  { id: 'food-emoji-36', title: '', value: '🌭' },
  { id: 'food-emoji-37', title: '', value: '🌮' },
  { id: 'food-emoji-38', title: '', value: '🌯' },
  { id: 'food-emoji-39', title: '', value: '🥙' },
  { id: 'food-emoji-40', title: '', value: '🥚' },
  { id: 'food-emoji-41', title: '', value: '🍳' },
  { id: 'food-emoji-42', title: '', value: '🥘' },
  { id: 'food-emoji-43', title: '', value: '🍲' },
  { id: 'food-emoji-44', title: '', value: '🥗' },
  { id: 'food-emoji-45', title: '', value: '🍿' },
  { id: 'food-emoji-46', title: '', value: '🍱' },
  { id: 'food-emoji-47', title: '', value: '🍘' },
  { id: 'food-emoji-48', title: '', value: '🍙' },
  { id: 'food-emoji-49', title: '', value: '🍚' },
  { id: 'food-emoji-50', title: '', value: '🍛' },
  { id: 'food-emoji-51', title: '', value: '🍜' },
  { id: 'food-emoji-52', title: '', value: '🍝' },
  { id: 'food-emoji-53', title: '', value: '🍠' },
  { id: 'food-emoji-54', title: '', value: '🍢' },
  { id: 'food-emoji-55', title: '', value: '🍣' },
  { id: 'food-emoji-56', title: '', value: '🍤' },
  { id: 'food-emoji-57', title: '', value: '🍥' },
  { id: 'food-emoji-58', title: '', value: '🍡' },
  { id: 'food-emoji-59', title: '', value: '🍦' },
  { id: 'food-emoji-60', title: '', value: '🍧' },
  { id: 'food-emoji-61', title: '', value: '🍨' },
  { id: 'food-emoji-62', title: '', value: '🍩' },
  { id: 'food-emoji-63', title: '', value: '🍪' },
  { id: 'food-emoji-64', title: '', value: '🎂' },
  { id: 'food-emoji-65', title: '', value: '🍰' },
  { id: 'food-emoji-66', title: '', value: '🍫' },
  { id: 'food-emoji-67', title: '', value: '🍬' },
  { id: 'food-emoji-68', title: '', value: '🍭' },
  { id: 'food-emoji-69', title: '', value: '🍮' },
  { id: 'food-emoji-70', title: '', value: '🍯' },
  { id: 'food-emoji-71', title: '', value: '🍼' },
  { id: 'food-emoji-72', title: '', value: '🥛' },
  { id: 'food-emoji-73', title: '', value: '☕' },
  { id: 'food-emoji-74', title: '', value: '🍵' },
  { id: 'food-emoji-75', title: '', value: '🍶' },
  { id: 'food-emoji-76', title: '', value: '🍾' },
  { id: 'food-emoji-77', title: '', value: '🍷' },
  { id: 'food-emoji-78', title: '', value: '🍸' },
  { id: 'food-emoji-79', title: '', value: '🍹' },
  { id: 'food-emoji-80', title: '', value: '🍺' },
  { id: 'food-emoji-81', title: '', value: '🍻' },
  { id: 'food-emoji-82', title: '', value: '🥂' },
  { id: 'food-emoji-83', title: '', value: '🥃' },
  { id: 'food-emoji-84', title: '', value: '🍽' },
  { id: 'food-emoji-85', title: '', value: '🍴' },
  { id: 'food-emoji-86', title: '', value: '🥄' },
  { id: 'food-emoji-87', title: '', value: '🔪' },
  { id: 'food-emoji-88', title: '', value: '🏺' },
  { id: 'food-emoji-89', title: '', value: '🥥' },
  { id: 'food-emoji-90', title: '', value: '🥦' },
  { id: 'food-emoji-91', title: '', value: '🥨' },
  { id: 'food-emoji-92', title: '', value: '🥩' },
  { id: 'food-emoji-93', title: '', value: '🥪' },
  { id: 'food-emoji-94', title: '', value: '🥣' },
  { id: 'food-emoji-95', title: '', value: '🥫' },
  { id: 'food-emoji-96', title: '', value: '🥟' },
  { id: 'food-emoji-97', title: '', value: '🥠' },
  { id: 'food-emoji-98', title: '', value: '🥡' },
  { id: 'food-emoji-99', title: '', value: '🥧' },
  { id: 'food-emoji-100', title: '', value: '🥤' },
  { id: 'food-emoji-101', title: '', value: '🥢' },
  // Activities
  { id: 'activities-emoji-0', title: '', value: '🎃' },
  { id: 'activities-emoji-1', title: '', value: '🎄' },
  { id: 'activities-emoji-2', title: '', value: '🎆' },
  { id: 'activities-emoji-3', title: '', value: '🎇' },
  { id: 'activities-emoji-4', title: '', value: '✨' },
  { id: 'activities-emoji-5', title: '', value: '🎈' },
  { id: 'activities-emoji-6', title: '', value: '🎉' },
  { id: 'activities-emoji-7', title: '', value: '🎊' },
  { id: 'activities-emoji-8', title: '', value: '🎋' },
  { id: 'activities-emoji-9', title: '', value: '🎍' },
  { id: 'activities-emoji-10', title: '', value: '🎎' },
  { id: 'activities-emoji-11', title: '', value: '🎏' },
  { id: 'activities-emoji-12', title: '', value: '🎐' },
  { id: 'activities-emoji-13', title: '', value: '🎑' },
  { id: 'activities-emoji-14', title: '', value: '🎀' },
  { id: 'activities-emoji-15', title: '', value: '🎁' },
  { id: 'activities-emoji-16', title: '', value: '🎗' },
  { id: 'activities-emoji-17', title: '', value: '🎟' },
  { id: 'activities-emoji-18', title: '', value: '🎫' },
  { id: 'activities-emoji-19', title: '', value: '🎖' },
  { id: 'activities-emoji-20', title: '', value: '🏆' },
  { id: 'activities-emoji-21', title: '', value: '🏅' },
  { id: 'activities-emoji-22', title: '', value: '🥇' },
  { id: 'activities-emoji-23', title: '', value: '🥈' },
  { id: 'activities-emoji-24', title: '', value: '🥉' },
  { id: 'activities-emoji-25', title: '', value: '⚽' },
  { id: 'activities-emoji-26', title: '', value: '⚾' },
  { id: 'activities-emoji-27', title: '', value: '🏀' },
  { id: 'activities-emoji-28', title: '', value: '🏐' },
  { id: 'activities-emoji-29', title: '', value: '🏈' },
  { id: 'activities-emoji-30', title: '', value: '🏉' },
  { id: 'activities-emoji-31', title: '', value: '🎾' },
  { id: 'activities-emoji-32', title: '', value: '🎳' },
  { id: 'activities-emoji-33', title: '', value: '🏏' },
  { id: 'activities-emoji-34', title: '', value: '🏑' },
  { id: 'activities-emoji-35', title: '', value: '🏒' },
  { id: 'activities-emoji-36', title: '', value: '🏓' },
  { id: 'activities-emoji-37', title: '', value: '🏸' },
  { id: 'activities-emoji-38', title: '', value: '🥊' },
  { id: 'activities-emoji-39', title: '', value: '🥋' },
  { id: 'activities-emoji-40', title: '', value: '🥅' },
  { id: 'activities-emoji-41', title: '', value: '⛳' },
  { id: 'activities-emoji-42', title: '', value: '⛸' },
  { id: 'activities-emoji-43', title: '', value: '🎣' },
  { id: 'activities-emoji-44', title: '', value: '🎽' },
  { id: 'activities-emoji-45', title: '', value: '🎿' },
  { id: 'activities-emoji-46', title: '', value: '🎯' },
  { id: 'activities-emoji-47', title: '', value: '🎱' },
  { id: 'activities-emoji-48', title: '', value: '🔮' },
  { id: 'activities-emoji-49', title: '', value: '🎮' },
  { id: 'activities-emoji-50', title: '', value: '🕹' },
  { id: 'activities-emoji-51', title: '', value: '🎰' },
  { id: 'activities-emoji-52', title: '', value: '🎲' },
  { id: 'activities-emoji-53', title: '', value: '♠' },
  { id: 'activities-emoji-54', title: '', value: '♥' },
  { id: 'activities-emoji-55', title: '', value: '♦' },
  { id: 'activities-emoji-56', title: '', value: '♣' },
  { id: 'activities-emoji-57', title: '', value: '🃏' },
  { id: 'activities-emoji-58', title: '', value: '🀄' },
  { id: 'activities-emoji-59', title: '', value: '🎴' },
  { id: 'activities-emoji-61', title: '', value: '🎭' },
  { id: 'activities-emoji-62', title: '', value: '🖼' },
  { id: 'activities-emoji-63', title: '', value: '🎨' },
  { id: 'activities-emoji-64', title: '', value: '🛷' },
  { id: 'activities-emoji-65', title: '', value: '🥌' },
  // Travel & Places
  { id: 'travel&place-emoji-0', title: '', value: '🌍' },
  { id: 'travel&place-emoji-1', title: '', value: '🌎' },
  { id: 'travel&place-emoji-2', title: '', value: '🌏' },
  { id: 'travel&place-emoji-3', title: '', value: ' ' },
  { id: 'travel&place-emoji-4', title: '', value: '🌐' },
  { id: 'travel&place-emoji-5', title: '', value: ' ' },
  { id: 'travel&place-emoji-6', title: '', value: '🗺' },
  { id: 'travel&place-emoji-7', title: '', value: ' ' },
  { id: 'travel&place-emoji-8', title: '', value: '🗾' },
  { id: 'travel&place-emoji-9', title: '', value: ' ' },
  { id: 'travel&place-emoji-10', title: '', value: '🏔' },
  { id: 'travel&place-emoji-11', title: '', value: '⛰' },
  { id: 'travel&place-emoji-12', title: '', value: '🌋' },
  { id: 'travel&place-emoji-13', title: '', value: '🗻' },
  { id: 'travel&place-emoji-14', title: '', value: '🏕' },
  { id: 'travel&place-emoji-15', title: '', value: ' ' },
  { id: 'travel&place-emoji-16', title: '', value: '🏖' },
  { id: 'travel&place-emoji-17', title: '', value: ' ' },
  { id: 'travel&place-emoji-18', title: '', value: '🏜' },
  { id: 'travel&place-emoji-19', title: '', value: ' ' },
  { id: 'travel&place-emoji-20', title: '', value: '🏝' },
  { id: 'travel&place-emoji-21', title: '', value: ' ' },
  { id: 'travel&place-emoji-22', title: '', value: '🏞' },
  { id: 'travel&place-emoji-23', title: '', value: ' ' },
  { id: 'travel&place-emoji-24', title: '', value: '🏟' },
  { id: 'travel&place-emoji-25', title: '', value: '🏛' },
  { id: 'travel&place-emoji-26', title: '', value: ' ' },
  { id: 'travel&place-emoji-27', title: '', value: '🏗' },
  { id: 'travel&place-emoji-28', title: '', value: ' ' },
  { id: 'travel&place-emoji-29', title: '', value: '🏘' },
  { id: 'travel&place-emoji-30', title: '', value: ' ' },
  { id: 'travel&place-emoji-31', title: '', value: '🏚' },
  { id: 'travel&place-emoji-32', title: '', value: ' ' },
  { id: 'travel&place-emoji-33', title: '', value: '🏠' },
  { id: 'travel&place-emoji-34', title: '', value: '🏡' },
  { id: 'travel&place-emoji-35', title: '', value: '🏢' },
  { id: 'travel&place-emoji-36', title: '', value: '🏣' },
  { id: 'travel&place-emoji-37', title: '', value: '🏤' },
  { id: 'travel&place-emoji-38', title: '', value: '🏥' },
  { id: 'travel&place-emoji-39', title: '', value: '🏦' },
  { id: 'travel&place-emoji-40', title: '', value: '🏨' },
  { id: 'travel&place-emoji-41', title: '', value: '🏩' },
  { id: 'travel&place-emoji-42', title: '', value: '🏪' },
  { id: 'travel&place-emoji-43', title: '', value: '🏫' },
  { id: 'travel&place-emoji-44', title: '', value: '🏬' },
  { id: 'travel&place-emoji-45', title: '', value: '🏭' },
  { id: 'travel&place-emoji-46', title: '', value: '🏯' },
  { id: 'travel&place-emoji-47', title: '', value: '🏰' },
  { id: 'travel&place-emoji-48', title: '', value: '💒' },
  { id: 'travel&place-emoji-49', title: '', value: '🗼' },
  { id: 'travel&place-emoji-50', title: '', value: '🗽' },
  { id: 'travel&place-emoji-51', title: '', value: '⛪' },
  { id: 'travel&place-emoji-52', title: '', value: '🕌' },
  { id: 'travel&place-emoji-53', title: '', value: '🕍' },
  { id: 'travel&place-emoji-54', title: '', value: '⛩' },
  { id: 'travel&place-emoji-55', title: '', value: '🕋' },
  { id: 'travel&place-emoji-56', title: '', value: '⛲' },
  { id: 'travel&place-emoji-57', title: '', value: '⛺' },
  { id: 'travel&place-emoji-58', title: '', value: '🌁' },
  { id: 'travel&place-emoji-59', title: '', value: '🌃' },
  { id: 'travel&place-emoji-60', title: '', value: '🏙' },
  { id: 'travel&place-emoji-61', title: '', value: '🌄' },
  { id: 'travel&place-emoji-62', title: '', value: '🌅' },
  { id: 'travel&place-emoji-63', title: '', value: '🌆' },
  { id: 'travel&place-emoji-64', title: '', value: '🌇' },
  { id: 'travel&place-emoji-65', title: '', value: '🌉' },
  { id: 'travel&place-emoji-66', title: '', value: '♨' },
  { id: 'travel&place-emoji-67', title: '', value: '🌌' },
  { id: 'travel&place-emoji-68', title: '', value: '🎠' },
  { id: 'travel&place-emoji-69', title: '', value: '🎡' },
  { id: 'travel&place-emoji-70', title: '', value: '🎢' },
  { id: 'travel&place-emoji-71', title: '', value: '💈' },
  { id: 'travel&place-emoji-72', title: '', value: '🎪' },
  { id: 'travel&place-emoji-73', title: '', value: '🚂' },
  { id: 'travel&place-emoji-74', title: '', value: '🚃' },
  { id: 'travel&place-emoji-75', title: '', value: '🚄' },
  { id: 'travel&place-emoji-76', title: '', value: '🚅' },
  { id: 'travel&place-emoji-77', title: '', value: '🚆' },
  { id: 'travel&place-emoji-78', title: '', value: '🚇' },
  { id: 'travel&place-emoji-79', title: '', value: '🚈' },
  { id: 'travel&place-emoji-80', title: '', value: '🚉' },
  { id: 'travel&place-emoji-81', title: '', value: '🚊' },
  { id: 'travel&place-emoji-82', title: '', value: '🚝' },
  { id: 'travel&place-emoji-83', title: '', value: '🚞' },
  { id: 'travel&place-emoji-84', title: '', value: '🚋' },
  { id: 'travel&place-emoji-85', title: '', value: '🚌' },
  { id: 'travel&place-emoji-86', title: '', value: '🚍' },
  { id: 'travel&place-emoji-87', title: '', value: '🚎' },
  { id: 'travel&place-emoji-88', title: '', value: '🚐' },
  { id: 'travel&place-emoji-89', title: '', value: '🚑' },
  { id: 'travel&place-emoji-90', title: '', value: '🚒' },
  { id: 'travel&place-emoji-91', title: '', value: '🚓' },
  { id: 'travel&place-emoji-92', title: '', value: '🚔' },
  { id: 'travel&place-emoji-93', title: '', value: '🚕' },
  { id: 'travel&place-emoji-94', title: '', value: '🚖' },
  { id: 'travel&place-emoji-95', title: '', value: '🚗' },
  { id: 'travel&place-emoji-96', title: '', value: '🚘' },
  { id: 'travel&place-emoji-97', title: '', value: '🚙' },
  { id: 'travel&place-emoji-98', title: '', value: '🚚' },
  { id: 'travel&place-emoji-99', title: '', value: '🚛' },
  { id: 'travel&place-emoji-100', title: '', value: '🚜' },
  { id: 'travel&place-emoji-101', title: '', value: '🚲' },
  { id: 'travel&place-emoji-102', title: '', value: '🛴' },
  { id: 'travel&place-emoji-103', title: '', value: '🛵' },
  { id: 'travel&place-emoji-104', title: '', value: '🚏' },
  { id: 'travel&place-emoji-105', title: '', value: '🛣' },
  { id: 'travel&place-emoji-106', title: '', value: '🛤' },
  { id: 'travel&place-emoji-107', title: '', value: '🛢' },
  { id: 'travel&place-emoji-108', title: '', value: '⛽' },
  { id: 'travel&place-emoji-109', title: '', value: '🚨' },
  { id: 'travel&place-emoji-110', title: '', value: '🚥' },
  { id: 'travel&place-emoji-111', title: '', value: '🚦' },
  { id: 'travel&place-emoji-112', title: '', value: '🛑' },
  { id: 'travel&place-emoji-113', title: '', value: '🚧' },
  { id: 'travel&place-emoji-114', title: '', value: '⚓' },
  { id: 'travel&place-emoji-115', title: '', value: '⛵' },
  { id: 'travel&place-emoji-116', title: '', value: '🛶' },
  { id: 'travel&place-emoji-117', title: '', value: '🚤' },
  { id: 'travel&place-emoji-118', title: '', value: ' ' },
  { id: 'travel&place-emoji-119', title: '', value: '🛳' },
  { id: 'travel&place-emoji-120', title: '', value: ' ' },
  { id: 'travel&place-emoji-121', title: '', value: '⛴' },
  { id: 'travel&place-emoji-122', title: '', value: '🛥' },
  { id: 'travel&place-emoji-123', title: '', value: '🚢' },
  { id: 'travel&place-emoji-124', title: '', value: ' ' },
  { id: 'travel&place-emoji-125', title: '', value: '✈' },
  { id: 'travel&place-emoji-126', title: '', value: '🛩' },
  { id: 'travel&place-emoji-127', title: '', value: '🛫' },
  { id: 'travel&place-emoji-128', title: '', value: '🛬' },
  { id: 'travel&place-emoji-129', title: '', value: '💺' },
  { id: 'travel&place-emoji-130', title: '', value: '🚁' },
  { id: 'travel&place-emoji-131', title: '', value: '🚟' },
  { id: 'travel&place-emoji-132', title: '', value: '🚠' },
  { id: 'travel&place-emoji-133', title: '', value: '🚡' },
  { id: 'travel&place-emoji-134', title: '', value: '🛰' },
  { id: 'travel&place-emoji-135', title: '', value: '🚀' },
  { id: 'travel&place-emoji-136', title: '', value: '🛎' },
  { id: 'travel&place-emoji-137', title: '', value: '⌛' },
  { id: 'travel&place-emoji-138', title: '', value: '⏳' },
  { id: 'travel&place-emoji-139', title: '', value: '⌚' },
  { id: 'travel&place-emoji-140', title: '', value: '⏰' },
  { id: 'travel&place-emoji-141', title: '', value: '⏱' },
  { id: 'travel&place-emoji-142', title: '', value: '⏲' },
  { id: 'travel&place-emoji-143', title: '', value: '🕰' },
  { id: 'travel&place-emoji-144', title: '', value: '🕛' },
  { id: 'travel&place-emoji-145', title: '', value: '🕧' },
  { id: 'travel&place-emoji-146', title: '', value: '🕐' },
  { id: 'travel&place-emoji-147', title: '', value: '🕜' },
  { id: 'travel&place-emoji-148', title: '', value: '🕑' },
  { id: 'travel&place-emoji-149', title: '', value: '🕝' },
  { id: 'travel&place-emoji-150', title: '', value: '🕒' },
  { id: 'travel&place-emoji-151', title: '', value: '🕞' },
  { id: 'travel&place-emoji-152', title: '', value: '🕓' },
  { id: 'travel&place-emoji-153', title: '', value: '🕟' },
  { id: 'travel&place-emoji-154', title: '', value: '🕔' },
  { id: 'travel&place-emoji-155', title: '', value: '🕠' },
  { id: 'travel&place-emoji-156', title: '', value: '🕕' },
  { id: 'travel&place-emoji-157', title: '', value: '🕡' },
  { id: 'travel&place-emoji-158', title: '', value: '🕖' },
  { id: 'travel&place-emoji-159', title: '', value: '🕢' },
  { id: 'travel&place-emoji-160', title: '', value: '🕗' },
  { id: 'travel&place-emoji-161', title: '', value: '🕣' },
  { id: 'travel&place-emoji-162', title: '', value: '🕘' },
  { id: 'travel&place-emoji-163', title: '', value: '🕤' },
  { id: 'travel&place-emoji-164', title: '', value: '🕙' },
  { id: 'travel&place-emoji-165', title: '', value: '🕥' },
  { id: 'travel&place-emoji-166', title: '', value: '🕚' },
  { id: 'travel&place-emoji-167', title: '', value: '🕦' },
  { id: 'travel&place-emoji-168', title: '', value: '🌑' },
  { id: 'travel&place-emoji-169', title: '', value: '🌒' },
  { id: 'travel&place-emoji-170', title: '', value: '🌓' },
  { id: 'travel&place-emoji-171', title: '', value: '🌔' },
  { id: 'travel&place-emoji-172', title: '', value: '🌕' },
  { id: 'travel&place-emoji-173', title: '', value: '🌖' },
  { id: 'travel&place-emoji-174', title: '', value: '🌗' },
  { id: 'travel&place-emoji-175', title: '', value: '🌘' },
  { id: 'travel&place-emoji-176', title: '', value: '🌙' },
  { id: 'travel&place-emoji-177', title: '', value: '🌚' },
  { id: 'travel&place-emoji-178', title: '', value: '🌛' },
  { id: 'travel&place-emoji-179', title: '', value: '🌜' },
  { id: 'travel&place-emoji-180', title: '', value: '🌡' },
  { id: 'travel&place-emoji-181', title: '', value: '☀' },
  { id: 'travel&place-emoji-182', title: '', value: '🌝' },
  { id: 'travel&place-emoji-183', title: '', value: '🌞' },
  { id: 'travel&place-emoji-184', title: '', value: '⭐' },
  { id: 'travel&place-emoji-185', title: '', value: '🌟' },
  { id: 'travel&place-emoji-186', title: '', value: '🌠' },
  { id: 'travel&place-emoji-187', title: '', value: '☁' },
  { id: 'travel&place-emoji-188', title: '', value: '⛅' },
  { id: 'travel&place-emoji-189', title: '', value: '⛈' },
  { id: 'travel&place-emoji-190', title: '', value: '🌤' },
  { id: 'travel&place-emoji-191', title: '', value: '🌥' },
  { id: 'travel&place-emoji-192', title: '', value: '🌦' },
  { id: 'travel&place-emoji-193', title: '', value: '🌧' },
  { id: 'travel&place-emoji-194', title: '', value: '🌨' },
  { id: 'travel&place-emoji-195', title: '', value: '🌩' },
  { id: 'travel&place-emoji-196', title: '', value: '🌪' },
  { id: 'travel&place-emoji-197', title: '', value: '🌫' },
  { id: 'travel&place-emoji-198', title: '', value: '🌬' },
  { id: 'travel&place-emoji-199', title: '', value: '🌀' },
  { id: 'travel&place-emoji-200', title: '', value: '🌈' },
  { id: 'travel&place-emoji-201', title: '', value: '🌂' },
  { id: 'travel&place-emoji-202', title: '', value: '☂' },
  { id: 'travel&place-emoji-203', title: '', value: '☔' },
  { id: 'travel&place-emoji-204', title: '', value: '⛱' },
  { id: 'travel&place-emoji-205', title: '', value: '⚡' },
  { id: 'travel&place-emoji-206', title: '', value: '❄' },
  { id: 'travel&place-emoji-207', title: '', value: '☃' },
  { id: 'travel&place-emoji-208', title: '', value: '⛄' },
  { id: 'travel&place-emoji-209', title: '', value: '☄' },
  { id: 'travel&place-emoji-210', title: '', value: '🔥' },
  { id: 'travel&place-emoji-211', title: '', value: '💧' },
  { id: 'travel&place-emoji-212', title: '', value: '🌊' },
  { id: 'travel&place-emoji-213', title: '', value: '🛸' },
]

// Objects
// 🔇🔈🔉🔊📢📣📯🔔
// 🔕🎼🎵🎶🎙🎚🎛🎤
// 🎧📻🎷🎸🎹🎺🎻🥁
// 📱📲☎📞📟📠🔋🔌
// 💻🖥🖨⌨🖱🖲💽💾
// 💿📀🎥🎞📽🎬📺📷
// 📸📹📼🔍🔎🕯💡🔦
// 🏮📔📕📖📗📘📙📚
// 📓📒📃📜📄📰🗞📑
// 🔖🏷💰💴💵💶💷💸
// 💳💹💱💲✉📧📨📩
// 📤📥📦📫📪📬📭📮
// 🗳✏✒🖋🖊🖌🖍📝
// 💼📁📂🗂📅📆🗒🗓
// 📇📈📉📊📋📌📍📎
// 🖇📏📐✂🗃🗄🗑🔒
// 🔓🔏🔐🔑🗝🔨⛏⚒
// 🛠🗡⚔🔫🏹🛡🔧🔩
// ⚙🗜⚖🔗⛓⚗🔬🔭
// 📡💉💊🚪🛏🛋🚽🚿
// 🛁🛒🚬⚰⚱🗿
// Symbols
// 🏧🚮🚰♿🚹🚺🚻🚼
// 🚾🛂🛃🛄🛅⚠🚸⛔
// 🚫🚳🚭🚯🚱🚷📵🔞
// ☢☣⬆↗➡↘⬇↙
// ⬅↖↕↔↩↪⤴⤵
// 🔃🔄🔙🔚🔛🔜🔝🛐
// ⚛🕉✡☸☯✝☦☪
// ☮🕎🔯♈♉♊♋♌
// ♍♎♏♐♑♒♓⛎
// 🔀🔁🔂▶⏩⏭⏯◀
// ⏪⏮🔼⏫🔽⏬⏸⏹
// ⏺⏏🎦🔅🔆📶📳📴
// ♀♂⚕♻⚜🔱📛🔰
// ⭕✅☑✔✖❌❎➕
// ➖➗➰➿〽✳✴❇
// ‼⁉❓❔❕❗〰©
// ®™#️⃣*️⃣0️⃣1️⃣2️⃣3️⃣
// 4️⃣5️⃣6️⃣7️⃣8️⃣9️⃣🔟💯
// 🔠🔡🔢🔣🔤🅰🆎🅱
// 🆑🆒🆓ℹ🆔Ⓜ🆕🆖
// 🅾🆗🅿🆘🆙🆚🈁🈂
// 🈷🈶🈯🉐🈹🈚🈲🉑
// 🈸🈴🈳㊗㊙🈺🈵▪
// ▫◻◼◽◾⬛⬜🔶
// 🔷🔸🔹🔺🔻💠🔘🔲
// 🔳⚪⚫🔴🔵
